import numpy as np
from scipy.stats import gamma as scipy_gamma
from scipy.stats import invgamma as scipy_invgamma
from scipy.stats import wishart as scipy_wishart
from scipy.stats import invwishart as scipy_invwishart

# Parameterization note for scipy.stats.gamma(a, loc=0, scale=1):
# 'a' is the shape parameter (alpha).
# 'scale' is the scale parameter (theta). PDF is f(x) ~ x^(a-1) * exp(-x/theta). Mean = a * theta.
# This matches Julia's Distributions.Gamma(shape, scale_theta).

def sample_gamma(shape: float, scale_theta: float, size: Optional[int] = None) -> Union[float, np.ndarray]:
    """
    Samples from a Gamma distribution.
    Matches the parameterization of Julia's Distributions.Gamma(shape, scale_theta),
    where shape is alpha and scale_theta is theta.
    Mean = shape * scale_theta.

    Args:
        shape: The shape parameter (alpha > 0).
        scale_theta: The scale parameter (theta > 0).
        size: The number of samples to draw. If None, returns a single float.

    Returns:
        A float or numpy array of samples.
    """
    if shape <= 0:
        raise ValueError("Shape parameter (alpha) must be > 0.")
    if scale_theta <= 0:
        raise ValueError("Scale parameter (theta) must be > 0.")

    return scipy_gamma.rvs(a=shape, scale=scale_theta, size=size)


# Parameterization note for scipy.stats.invgamma(a, loc=0, scale=1):
# 'a' is the shape parameter (alpha).
# 'scale' is the scale parameter (beta in some notations). PDF f(x) ~ x^(-a-1) * exp(-scale/x).
# Mean = scale / (a - 1) for a > 1.
# This is a common parameterization for Inverse Gamma.

def sample_inverse_gamma(shape: float, scale_param: float, size: Optional[int] = None) -> Union[float, np.ndarray]:
    """
    Samples from an Inverse Gamma distribution.
    Parameterized by shape (alpha) and scale (beta).
    Mean = scale_param / (shape - 1) for shape > 1.

    Args:
        shape: The shape parameter (alpha > 0).
        scale_param: The scale parameter (beta > 0).
        size: The number of samples to draw. If None, returns a single float.

    Returns:
        A float or numpy array of samples.
    """
    if shape <= 0:
        raise ValueError("Shape parameter (alpha) must be > 0.")
    if scale_param <= 0:
        raise ValueError("Scale parameter (beta) must be > 0.")

    return scipy_invgamma.rvs(a=shape, scale=scale_param, size=size)


def sample_scaled_inverse_chi_squared(df: float, scale_sq: float, size: Optional[int] = None) -> Union[float, np.ndarray]:
    """
    Samples from a Scaled Inverse Chi-squared distribution.
    A variable x ~ ScaledInvChi2(df, scale_sq) can be generated by:
    1. Sampling w ~ ChiSquared(df)
    2. x = df * scale_sq / w
    Alternatively, ScaledInvChi2(df, scale_sq) is equivalent to InvGamma(df/2, df * scale_sq / 2).

    Args:
        df: Degrees of freedom (nu > 0).
        scale_sq: The scale parameter S^2 (prior sum of squares / df, or prior variance).
        size: Number of samples.

    Returns:
        A float or numpy array of samples.
    """
    if df <= 0:
        raise ValueError("Degrees of freedom (df) must be > 0.")
    if scale_sq <= 0:
        raise ValueError("Scale parameter (scale_sq) must be > 0.")

    # Using the InvGamma equivalence: shape = df/2, scale_param = df * scale_sq / 2
    ig_shape = df / 2.0
    ig_scale = (df * scale_sq) / 2.0

    return sample_inverse_gamma(shape=ig_shape, scale_param=ig_scale, size=size)


def sample_inverse_wishart(df: float, scale_matrix: np.ndarray, size: Optional[int] = None) -> Union[np.ndarray, List[np.ndarray]]:
    """
    Samples from an Inverse Wishart distribution.
    Scipy's invwishart(df, scale) uses df and a scale matrix.
    The scale matrix is often denoted Psi in literature (the sum of squares matrix).
    Mean = scale_matrix / (df - p - 1) where p is dim of matrix, for df > p + 1.

    Args:
        df: Degrees of freedom (must be > p - 1, where p is dimension of scale_matrix).
        scale_matrix: The scale matrix (symmetric positive definite, p x p).
        size: Number of samples to draw. If None, returns a single matrix.
              If size is provided, returns a list of matrices if size > 1, or array of shape (size, p, p)
              (scipy behavior: if size > 1, returns (size, p, p); if size=1, (1,p,p); if None, (p,p))


    Returns:
        A p x p matrix or an array of p x p matrices.
    """
    if not isinstance(scale_matrix, np.ndarray) or scale_matrix.ndim != 2 or scale_matrix.shape[0] != scale_matrix.shape[1]:
        raise ValueError("scale_matrix must be a square 2D numpy array.")

    p = scale_matrix.shape[0]
    if df <= p - 1:
        raise ValueError(f"Degrees of freedom (df) must be > {p-1} (dimension - 1).")

    # Check for positive definiteness (simple check, not exhaustive)
    if not np.all(np.linalg.eigvals(scale_matrix) > 0):
        raise ValueError("scale_matrix must be positive definite.")

    # Scipy's invwishart.rvs returns shape (size, p, p) if size is not None,
    # and (p,p) if size is None.
    return scipy_invwishart.rvs(df=df, scale=scale_matrix, size=size)


# Example usage (for testing if run directly)
if __name__ == '__main__':
    print("Testing distribution samplers:")

    # Gamma
    gamma_sample = sample_gamma(shape=2.0, scale_theta=3.0)
    print(f"Gamma(2,3) sample: {gamma_sample}") # Mean = 6
    gamma_samples = sample_gamma(shape=2.0, scale_theta=3.0, size=5)
    print(f"Gamma(2,3) 5 samples: {gamma_samples}")

    # Inverse Gamma
    inv_gamma_sample = sample_inverse_gamma(shape=3.0, scale_param=2.0)
    print(f"InvGamma(3,2) sample: {inv_gamma_sample}") # Mean = 2 / (3-1) = 1
    inv_gamma_samples = sample_inverse_gamma(shape=3.0, scale_param=2.0, size=5)
    print(f"InvGamma(3,2) 5 samples: {inv_gamma_samples}")

    # Scaled Inverse Chi-squared
    scaled_inv_chi2_sample = sample_scaled_inverse_chi_squared(df=4.0, scale_sq=1.5)
    # Equivalent to InvGamma(df/2, df*scale_sq/2) = InvGamma(2, 4*1.5/2=3)
    # Mean = 3 / (2-1) = 3
    print(f"ScaledInvChi2(df=4, scale_sq=1.5) sample: {scaled_inv_chi2_sample}")
    scaled_inv_chi2_samples = sample_scaled_inverse_chi_squared(df=4.0, scale_sq=1.5, size=5)
    print(f"ScaledInvChi2(df=4, scale_sq=1.5) 5 samples: {scaled_inv_chi2_samples}")

    # Inverse Wishart
    p_dim = 3
    df_iw = float(p_dim + 2) # df > p - 1. Let df = p+2 = 5 for mean calculation.
    scale_mat_iw = np.array([[2.0, 0.5, 0.2],
                             [0.5, 1.5, 0.3],
                             [0.2, 0.3, 1.0]])
    if not np.all(np.linalg.eigvals(scale_mat_iw) > 0):
        print("Error: Scale matrix for IW test is not positive definite.")
    else:
        inv_wishart_sample = sample_inverse_wishart(df=df_iw, scale_matrix=scale_mat_iw)
        print(f"InvWishart(df={df_iw}, scale_matrix) sample:\n{inv_wishart_sample}")
        # Mean = scale_mat_iw / (df_iw - p_dim - 1) = scale_mat_iw / (5 - 3 - 1) = scale_mat_iw / 1
        print(f"Expected Mean:\n{scale_mat_iw / (df_iw - p_dim - 1)}")

        inv_wishart_samples = sample_inverse_wishart(df=df_iw, scale_matrix=scale_mat_iw, size=2)
        print(f"InvWishart(df={df_iw}, scale_matrix) 2 samples (shape {inv_wishart_samples.shape}):\n{inv_wishart_samples}")

    # Test error conditions
    try: sample_gamma(0,1)
    except ValueError as e: print(f"Caught expected error: {e}")
    try: sample_inverse_gamma(1,0)
    except ValueError as e: print(f"Caught expected error: {e}")
    try: sample_scaled_inverse_chi_squared(0,1)
    except ValueError as e: print(f"Caught expected error: {e}")
    try: sample_inverse_wishart(df=p_dim-1, scale_matrix=np.eye(p_dim)) # df too small
    except ValueError as e: print(f"Caught expected error: {e}")
    try: sample_inverse_wishart(df=p_dim+1, scale_matrix=np.array([[1,0],[0,0]])) # Not PD
    except ValueError as e: print(f"Caught expected error: {e}")

from typing import Union, Optional # Ensure these are at the top for the type hints
```
